import time

time.sleep(0.1)
print("Establishing conection with server.")
time.sleep(.2)
print("Establishing conection with server..")
time.sleep(.2)
print("Establishing conection with server...")
time.sleep(.2)
print("Establishing conection with server....")
time.sleep(1.25)
print("Downloading Packages: 000/100 mb")
time.sleep(2)
print("Downloading Packages: 020/100 mb @ 20 mb/s")
time.sleep(1)
print("Downloading Packages: 040/100 mb @ 20 mb/s")
time.sleep(1)
print("Downloading Packages: 060/100 mb @ 20 mb/s")
time.sleep(1)
print("Downloading Packages: 080/100 mb @ 20 mb/s")
time.sleep(1)
print("Downloading Packages: 099/100 mb @ 20 mb/s")
time.sleep(1)
print("Downloading Packages: 100/100 mb @ 1 mb/s")
time.sleep(2)
print("MD5 check results: Matching")
time.sleep(1)
print("Installing...")
time.sleep(2)
print("")
print("")
print("Installation successful, you may now use hackingTools")